attention_head_size: 1
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: true
  add_target_scales: true
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AAAAAAAAAAA=
      warn: true
    group: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AAAAAAAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group
  lags: null
  max_encoder_length: 30
  max_prediction_length: 1
  min_encoder_length: 30
  min_prediction_idx: 0
  min_prediction_length: 1
  predict_mode: false
  randomize_length: null
  scalers:
    day_of_week: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - day_of_week
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAAAAAAAAEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          zTt/Zp6g9j8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAEA=
      with_mean: true
      with_std: true
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    position_normalized: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - position_normalized
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          ZmZmZmZm3j8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          VtF5EkiP0j8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          3f4gQ2WHtT8=
      with_mean: true
      with_std: true
    price: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - price
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          mjcSZvIH3j8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          i9TX26vXyz8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          XFbxk585qD8=
      with_mean: true
      with_std: true
    relative_time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - relative_time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    target_center: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - target_center
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          z/YOdyYr6r8=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    target_scale: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - target_scale
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          d5WRjmoZAEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.5.1
      copy: true
      feature_names_in_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - time_idx
      mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAADwaEA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        kAEAAAAAAAA=
      scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          5n8zcw/eXEA=
      var_: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAKAKykA=
      with_mean: true
      with_std: true
  static_categoricals: null
  static_reals: null
  target: target
  target_normalizer: &id006 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups:
    - group
    _method_kwargs: {}
    center: true
    groups:
    - group
    method: standard
    method_kwargs: {}
    missing_:
      center: -0.8177673650131624
      scale: 2.0124102724245705
    norm_: !!python/object:pandas.core.frame.DataFrame
      _flags:
        allows_duplicate_labels: true
      _metadata: []
      _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
      - !!python/tuple
        - !!python/object/apply:pandas._libs.internals._unpickle_block
          - !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id002
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
              - 1
            - *id003
            - false
            - !!binary |
              zfYOdyYr6r93lZGOahkAQA==
          - !!python/object/apply:builtins.slice
            - 0
            - 2
            - 1
          - 2
      - - !!python/object/apply:pandas.core.indexes.base._new_Index
          - &id005 !!python/name:pandas.core.indexes.base.Index ''
          - data: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - *id002
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 2
              - *id004
              - false
              - - center
                - scale
            name: null
        - !!python/object/apply:pandas.core.indexes.base._new_Index
          - *id005
          - data: !!python/object/apply:numpy.core.multiarray._reconstruct
              args:
              - *id002
              - !!python/tuple
                - 0
              - !!binary |
                Yg==
              state: !!python/tuple
              - 1
              - !!python/tuple
                - 1
              - !!python/object/apply:numpy.dtype
                args:
                - i4
                - false
                - true
                state: !!python/tuple
                - 3
                - <
                - null
                - null
                - null
                - -1
                - -1
                - 0
              - false
              - !!binary |
                AAAAAA==
            name: group
      _typ: dataframe
      attrs: {}
    scale_by_group: false
    transformation: softplus
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - time_idx
  - day_of_week
  - position_normalized
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - price
  variable_groups: null
  weight: null
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 30
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id006
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
- target_center
- target_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
- day_of_week
- position_normalized
- relative_time_idx
time_varying_reals_encoder:
- time_idx
- day_of_week
- position_normalized
- relative_time_idx
- price
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- target_center
- target_scale
- time_idx
- day_of_week
- position_normalized
- relative_time_idx
- price
